# Generated by Django 5.0.6 on 2024-07-18 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_urlencurtada'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 20, 33, 4, 600138, tzinfo=datetime.timezone.utc)),
        ),
    ]
