# Generated by Django 5.0.6 on 2024-07-20 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_link_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='urlEncurtada',
            field=models.URLField(auto_created=True, blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 6, 30, 5, 337416, tzinfo=datetime.timezone.utc)),
        ),
    ]
