# Generated by Django 5.0.6 on 2024-07-20 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0012_alter_link_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='urlEncurtada',
            field=models.CharField(auto_created=True, blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 6, 51, 42, 879574, tzinfo=datetime.timezone.utc)),
        ),
    ]
